apiVersion: v1
kind: Secret
metadata:
  name: dreams-app-secrets
  labels:
    app: dreams-website-deployment
type: Opaque
stringData:
  # Email Service Configuration
  CONTACT_EMAIL: "dreamscollectiveorg@gmail.com"
  GOOGLE_APP_PW: "calb hgsf elue yfsu"
  EMAIL_RECIPIENT: "dreamscollectiveorg@gmail.com"
  
  # AWS Credentials
  # Note: If using IAM roles in EKS, these may not be needed
  # If you need explicit credentials, uncomment and fill in:
  # AWS_ACCESS_KEY_ID: "your-aws-access-key-id"
  # AWS_SECRET_ACCESS_KEY: "your-aws-secret-access-key"
  AWS_PROFILE: "dreams-dev"
  
  # Database Credentials
  DB_HOST: "dreams-main.ch66csoqs32t.us-east-2.rds.amazonaws.com"
  DB_USER: "admin"
  DB_PASSWORD: "dreams-pw-rds-1"
  DB_NAME: "dreams_main"
